// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using SSH_FrontEnd.Models.Common;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SSH_FrontEnd.Models;

public partial class FlowerArrangementType: IHasIdAndName
{
    [Key]
    public int FlowerArrangementTypeId { get; set; }
    public int Id => FlowerArrangementTypeId;
    public string Name { get; set; }

    public virtual ICollection<FlowerArrangement> FlowerArrangements { get; set; } = new List<FlowerArrangement>();


}